export const VEHICLES = [
  {
    id: 'toyota-camry',
    name: 'Toyota Camry',
    passengers: 4,
    luggage: 4,
    description: 'Reliable and comfortable sedan, perfect for city transfers and business travel.',
    image: '/ksa-images/Standard Class Taxi.png',
    basePrice: 85.00,
    discountPrice: null,
  },
  {
    id: 'mercedes-s-class',
    name: 'Mercedes S-Class',
    passengers: 4,
    luggage: 4,
    description: 'Luxury flagship sedan offering the ultimate in comfort and prestige for executive travel.',
    image: '/ksa-images/First Class Transfer.png',
    basePrice: 195.00,
    discountPrice: null,
  },
  {
    id: 'gmc-yukon',
    name: 'GMC Yukon',
    passengers: 8,
    luggage: 8,
    description: 'Premium SUV with generous legroom and luggage capacity — ideal for executive group travel.',
    image: '/ksa-images/SUV Limo Class.png',
    basePrice: 165.00,
    discountPrice: null,
  },
  {
    id: 'hyundai-starex-star-x',
    name: 'Hyundai Starex (Star X)',
    passengers: 11,
    luggage: 11,
    description: 'Spacious MPV offering comfortable seating for larger groups and smooth airport transfers.',
    image: '/ksa-images/Standard Van Transfer.png',
    basePrice: 115.00,
    discountPrice: null,
  },
  {
    id: 'hyundai-staria',
    name: 'Hyundai Staria',
    passengers: 8,
    luggage: 8,
    description: 'Modern and futuristic MPV providing premium comfort and ample space for families.',
    image: '/ksa-images/First Class Van Transfer.png',
    basePrice: 125.00,
    discountPrice: null,
  },
  {
    id: 'mercedes-sprinter',
    name: 'Mercedes Sprinter',
    passengers: 14,
    luggage: 14,
    description: 'High-capacity van suitable for large groups and long-distance transfers with roomy luggage space.',
    image: '/ksa-images/Minibus 12 Pax.png',
    basePrice: 245.00,
    discountPrice: null,
  },
];
