export const VEHICLES = [
  {
    id: 'toyota-camry',
    name: 'Toyota Camry',
    passengers: 4,
    luggage: 4,
    description: 'Reliable and comfortable sedan, perfect for city transfers and business travel.',
    image: '/ksa-images/toyota%20camry%202025.png',
    basePrice: 85.00,
    discountPrice: null,
  },
  {
    id: 'mercedes-s-class',
    name: 'Mercedes S-Class',
    passengers: 4,
    luggage: 4,
    description: 'Luxury flagship sedan offering the ultimate in comfort and prestige for executive travel.',
    image: '/ksa-images/mercedes%20S-class.png',
    basePrice: 195.00,
    discountPrice: null,
  },
  {
    id: 'gmc-yukon',
    name: 'GMC Yukon',
    passengers: 8,
    luggage: 8,
    description: 'Premium SUV with generous legroom and luggage capacity — ideal for executive group travel.',
    image: '/ksa-images/GMC%20Yukon.png',
    basePrice: 165.00,
    discountPrice: null,
  },
  {
    id: 'hyundai-starex-star-x',
    name: 'Hyundai Starex (Star X)',
    passengers: 11,
    luggage: 11,
    description: 'Spacious MPV offering comfortable seating for larger groups and smooth airport transfers.',
    image: '/ksa-images/Hyundai%20Star%20X.png',
    basePrice: 115.00,
    discountPrice: null,
  },
  {
    id: 'hyundai-staria',
    name: 'Hyundai Staria',
    passengers: 8,
    luggage: 8,
    description: 'Modern and futuristic MPV providing premium comfort and ample space for families.',
    image: '/ksa-images/Hyundai%20Staria.png',
    basePrice: 125.00,
    discountPrice: null,
  },
  {
    id: 'mercedes-sprinter',
    name: 'Mercedes Sprinter',
    passengers: 14,
    luggage: 14,
    description: 'High-capacity van suitable for large groups and long-distance transfers with roomy luggage space.',
    image: '/ksa-images/mercedes%20sprinter.png',
    basePrice: 245.00,
    discountPrice: null,
  },
];
